### PR TITLE
fix: Lint JS/TS files at root project folder level (#35)

### PR DESCRIPTION
**Pull request by yokuze**

### CODE REVIEW

**Review by jthomerson — CHANGES_REQUESTED** [review]
Will we ever have `./*.ts` files (at the root)?

**Comment by yokuze** [comment]
I thought about that too - it's technically possible, but it would have to be something that we either 1) run with `ts-node` rather than `node` (which we don't really do), because we don't have tsconfig set up to support `ts` files in the root, or 2) `import` it from `src` or `test` (but that has the same problem, our tsconfig files aren't set up to support ts files in the root and so those files would not be type checked when we run `grunt standards`).

Given the above, it didn't seem likely that we would have `./*.ts` files, so I didn't add it. That said, it doesn't cost much to add it if you'd rather it be future proof.

**Comment by jthomerson** [comment]
Since we support it with JS, it means we're loading a footgun not to support it with TS... someone will add some odd TS file in their root, and won't think about adding it to the Grunt list. Let's future proof ourselves.

**Comment by yokuze** [comment]
Updated - we now lint `./*.ts` files.

**Review by jthomerson — APPROVED** [review]

**Pull request merged**
